// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FINDMATCHREQUEST_FLATPACKET_H_
#define FLATBUFFERS_GENERATED_FINDMATCHREQUEST_FLATPACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace FlatPacket {

struct FindMatchRequest;
struct FindMatchRequestBuilder;

struct FindMatchRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FindMatchRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UUID = 4
  };
  int32_t uuid() const {
    return GetField<int32_t>(VT_UUID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_UUID, 4) &&
           verifier.EndTable();
  }
};

struct FindMatchRequestBuilder {
  typedef FindMatchRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uuid(int32_t uuid) {
    fbb_.AddElement<int32_t>(FindMatchRequest::VT_UUID, uuid, 0);
  }
  explicit FindMatchRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FindMatchRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FindMatchRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FindMatchRequest> CreateFindMatchRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t uuid = 0) {
  FindMatchRequestBuilder builder_(_fbb);
  builder_.add_uuid(uuid);
  return builder_.Finish();
}

inline const FlatPacket::FindMatchRequest *GetFindMatchRequest(const void *buf) {
  return ::flatbuffers::GetRoot<FlatPacket::FindMatchRequest>(buf);
}

inline const FlatPacket::FindMatchRequest *GetSizePrefixedFindMatchRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FlatPacket::FindMatchRequest>(buf);
}

inline bool VerifyFindMatchRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FlatPacket::FindMatchRequest>(nullptr);
}

inline bool VerifySizePrefixedFindMatchRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FlatPacket::FindMatchRequest>(nullptr);
}

inline void FinishFindMatchRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FlatPacket::FindMatchRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFindMatchRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FlatPacket::FindMatchRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FlatPacket

#endif  // FLATBUFFERS_GENERATED_FINDMATCHREQUEST_FLATPACKET_H_
